name: Merge to main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      nix: ${{ steps.filter.outputs.nix }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Detect changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d
        id: filter
        with:
          filters: |
            nix:
              - '*.nix'
              - 'overlays/**'
              - 'packages/**'
              - 'shells/**'

  build-and-push-nix:
    name: Build and push Nix packages
    needs: changes
    if: needs.changes.outputs.nix == 'true'
    permissions:
      contents: read
    uses: $/.github/workflows/nix.build-and-push.yaml
